name: Deploy Infrastructure Manually

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform
      
      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: terraform
      
      - name: Extract Instance IP
        run: |
          INSTANCE_IP=$(terraform output -raw instance_ip)
          echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV
        working-directory: terraform

      - name: Configure SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ansible/my-key.pem
          chmod 600 ansible/my-key.pem

      - name: Configure Ansible Inventory
        run: |
          echo "[web]" > ansible/inventory
          echo "$INSTANCE_IP ansible_user=ubuntu ansible_ssh_private_key_file=ansible/my-key.pem" >> ansible/inventory

      - name: Debug Ansible Inventory
        run: cat ansible/inventory

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory ansible/playbook.yml
